### PR TITLE
Reuse db and remove old file before write

### PR DESCRIPTION
**Pull request by marmiky**
Hi, you did a very useful tool. 
I use it on my linux server and my windows workstation.

I did this 2 changes

- I use big db file (200MB+) and reading it 2 times (on read_db and write_db) use a lot of memory.
I think is possible to reuse the initial db and low the memory usage.
I reuse the db dictionary for writing the new db

- On windows renaming the temp file on an existing db give a error so i check if the file exist and i delete it

### CODE REVIEW

**Comment by trapexit** [comment]
The reason I don't reuse the db is because if your run multiple instances at the same time you have one clobber the other. Doing it this way limits any race conditions. 

Rename is required to have it work atomically. Does Windows not support atomic rename?

**Comment by marmiky** [comment]
Ok you are right on multiple instance. I use only one. But why it use to much memory? when i work with my 200mb db python x64 uses 2gb memory (windows & linux) when writing final file. May be st objects uses it?

On windows when you rename the tmp file to destination file and destination file exist it gives WinError 183.
I delete it before. I see it on python 3.61. I will try on other versions.

**Comment by trapexit** [comment]
I've not looked into the memory consumption. I'm guessing it's just that it's a lot of data that needs to be pickled. I could look into serializing the data in a more efficient manner. 

What's error 183?

**Comment by marmiky** [comment]
Ok no problem i will try someting to understand where it use all that memory.

[WinError 183] Cannot create a file when that file already exists. On linux this error dont happens

**Comment by trapexit** [comment]
I'm not sure what to do about the windows issue. I'll have to read more about Windows and file manipulation. On Unix rename is atomic and the behavior is required for certain behaviors to work. As for memory I'll see what I can do. It'd possibly require changing to a proper db (sqlite3) but I was trying not to have dependencies.

**Comment by marmiky** [comment]
Check the pyton docs: https://docs.python.org/3/library/os.html#os.rename
It say "On Windows, if dst already exists, OSError will be raised even if it is a file."
I tested this shutil.move on windows and it works: https://docs.python.org/3/library/shutil.html#shutil.move
May be this is good also for you because "If the destination is on the current filesystem, then os.rename() is used."

For memory usage i did some test:

I put inside the db only data used by scorch (st_mode, st_size, st_mtime)

When reading the full db (full st objects) python x64 normally uses 1.2GB
When reading only hashes and that data as object (one object conteining that 3 data) 651MB
When reading hashes and the 3 data alone (no objects) 330mb

I think the best is the simplest: a db containing distinct values (hash value + st_mode + st_size + st_mtime). I try to change it in my fork

I agree dont use 3rd party libs for this.

**Comment by trapexit** [comment]
It's probably better for me to just use json or csv. Let me play with both of them and see what works best.  I'll also limit the data stored to limit memory and disk usage.

**Comment by marmiky** [comment]
Ok, i did a change. Now i try a bit to solve memory problems. See you.

**Comment by trapexit** [comment]
https://github.com/trapexit/scorch/tree/csv

can you try out the csv branch? I switched it to use csv as the disk format, limited the data stored in memory and on disk, it will convert the old format automatically, and moved to use os.replace rather than rename which should work on Windows.

**Comment by marmiky** [comment]
After load python uses 380Mb(win) and 460mb(linux). 
The db file is smaller(103MB) and compressed is very small (36MB!)
You must use utf-8 and set a correct newline on read and write (open(filepath,'r / w',newline='',encoding='utf-8'))
On windows without newline write 0D 2 times at end line.
You have a bug on read_db (after catching ex return the db)
The file is readable and usable by other programs. I think i will use it too.
Replace works also on win
Good work!

**Comment by trapexit** [comment]
Thanks for the tips wrt Windows. I'm familiar with the \n and \n\r expectations but rarely fool with Windows. How's the newly pushed version look?

**Comment by marmiky** [comment]
I think its ok!
Next days i will try it
Good evening from italy :)

**Pull request closed without merging**
